### ISSUE TITLE
How to get tabs like on picture?

### ISSUE THREAD

**Issue by markogresak** [stoeffel/material-iterm#2]
I have the latest version of stable iTerm (2.1.1) and I can't figure out how to set tabs like this, I only have 4 options and none look nice.

**Comment by stoeffel** [comment]
I think it's only available in the nightly build.

**Comment by markogresak** [comment]
That's right, I've now installed the nightly build and the tabs looks much nicer. Thanks!

**Comment by stoeffel** [comment]
Np.
